apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  annotations:
  name: grafanadatasource-prometheus
  namespace: monitoring
spec:
  allowCrossNamespaceImport: true
  datasource:
    access: proxy
    editable: true
    secureJsonData:
      httpHeaderValue1: Bearer <your token here>
    name: prometheus
    url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
    jsonData:
      httpHeaderName1: Authorization
      timeInterval: 5s
      tlsSkipVerify: true
    basicAuth: false
    isDefault: true
    type: prometheus
  instanceSelector:
    matchLabels:
      dashboards: grafana
  plugins:
    - name: grafana-clock-panel
      version: 1.3.0
  resyncPeriod: 5m
